#ifndef LIBPIXIE_DEFINITIONS_HH
#define LIBPIXIE_DEFINITIONS_HH

#define MAX_EVENTS 2
#define MAX_MEAS_PER_EVENT 500
#define MAX_TRACE_MEAS 20
#define MAX_CHANNELS_PER_BOARD 16
#define MAX_SLOTS_PER_CRATE 13
#define MAX_CRATES 2
#define MAX_TRACE_LENGTH 2500 

#define ROOT_COMPILE 1 

#endif
